class CfgWLRequisitionPresets
{
	class A3ReduxAll
	{
		class WEST
		{
			class Infantry
			{
				class B_Soldier_F 							{cost = 20;		requirements[]={};	};	// "Rifleman"
				class B_soldier_PG_F						{cost = 25;		requirements[]={};	};	// "Para Trooper"
				class B_CTRG_Soldier_tna_F					{cost = 30;		requirements[]={};	};	// "CTRG Scout"
				class B_crew_F 								{cost = 15;		requirements[]={};	};	// "Crewman"
				class B_Helipilot_F 						{cost = 10;		requirements[]={};	};	// "Helicopter Pilot"
				class B_Pilot_F 							{cost = 10;		requirements[]={};	};	// "Pilot"
				class B_Soldier_GL_F 						{cost = 50;		requirements[]={};	};	// "Grenadier"				
				class B_medic_F								{cost = 20;		requirements[]={};	};	// "Combat Life Saver"
				class B_soldier_AR_F						{cost = 50;		requirements[]={};	};	// "Autorifleman"
				class B_Soldier_A_F							{cost = 25;		requirements[]={};	};	// "Ammo Bearer"
				class B_soldier_M_F							{cost = 60;		requirements[]={};	};	// "Marksman"
				class B_soldier_repair_F					{cost = 100;	requirements[]={};	};	// "Repair Specialist"
				class B_HeavyGunner_F						{cost = 80;		requirements[]={};	};	// "Heavy Gunner"
				class B_soldier_LAT_F						{cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class B_soldier_LAT2_F						{cost = 100;	requirements[]={};	};	// "Rifleman (Light AT)"
				class B_CTRG_Soldier_LAT_tna_F 				{cost = 150;	requirements[]={};	};	// "Rifleman (Light AT)"
				class B_soldier_AT_F						{cost = 150;	requirements[]={};	};	// "Missile Specialist (AT)"
				class B_soldier_AA_F						{cost = 150;	requirements[]={};	};	// "Missile Specialist (AA)"
				class B_Sharpshooter_F						{cost = 80;		requirements[]={};	};	// "Sharpshooter"
				class B_sniper_F							{cost = 100;	requirements[]={};	};	// "Sniper"
				class B_Captain_Dwarden_F					{cost = 150;	requirements[]={};	};	// "Dwarden"
			};
			class Vehicles
			{
				class B_Quadbike_01_F						{cost =  20;	requirements[]={};	};	// "Quad Bike"
				class B_LSV_01_unarmed_F					{cost = 100;	requirements[]={};	};	// "Prowler (Unarmed)"
				class B_MRAP_01_F							{cost = 300;	requirements[]={};	};	// "Hunter"
				class B_LSV_01_armed_F						{cost = 350;	requirements[]={};	};	// "Prowler (HMG)"
				class B_G_Offroad_01_armed_F				{cost = 200;	requirements[]={};	};	// "Offroad (HMG)"
				class B_LSV_01_AT_F							{cost = 1500;	requirements[]={};	};	// "Prowler (AT)"
				class B_G_Offroad_01_AT_F					{cost = 500;	requirements[]={};	};	// "Offroad (AT)"
				class B_MRAP_01_hmg_F						{cost = 1000;	requirements[]={};	};	// "Hunter HMG"
				class B_MRAP_01_gmg_F						{cost = 1200;	requirements[]={};	};	// "Hunter GMG"
				class B_Truck_01_ammo_F						{cost = 2500;	requirements[]={};	};	// "HEMTT Ammo"
				class B_Truck_01_Repair_F					{cost = 2000;	requirements[]={};	};	// "HEMTT Repair"
				class B_Truck_01_fuel_F						{cost = 500;	requirements[]={};	};	// "HEMTT Fuel"
				class O_T_Truck_03_device_ghex_F            {cost = 2500;	requirements[]={};	};	// "Tempest Device"
				class B_Truck_01_transport_F				{cost = 200;	requirements[]={};	};	// "HEMTT Transport"
				class B_Truck_01_flatbed_F					{cost = 700;	requirements[]={};	};	// "HEMTT Flatbed"	
				class B_APC_Wheeled_03_cannon_F				{cost = 3500;	requirements[]={};	};	// "BLUFOR Gorgon"
				class B_APC_Wheeled_01_cannon_F				{cost = 2200;	requirements[]={};	};	// "AMV-7 Marshall"
				class B_APC_Tracked_01_rcws_F				{cost = 1800;	requirements[]={};	};	// "IFV-6c Panther"
				class B_APC_Tracked_01_AA_F					{cost = 5000;	requirements[]={};	};	// "IFV-6a Cheetah"
				class B_MBT_01_cannon_F						{cost = 7000;	requirements[]={};	};	// "M2A1 Slammer"
				class B_MBT_01_TUSK_F						{cost = 9000;	requirements[]={};	};	// "M2A1 Slammer UP"
				class B_AFV_Wheeled_01_cannon_F				{cost = 5500;	requirements[]={};	};	// "Rhino MGS"
				class B_AFV_Wheeled_01_up_cannon_F			{cost = 6500;	requirements[]={};	};	// "Rhino MGS UP" 
				class B_MBT_01_arty_F						{cost = 20000;	requirements[]={};	};	// "M4 Scorcher"
				class B_MBT_01_mlrs_F						{cost = 25000;	requirements[]={};	};	// "M5 Sandstorm MLRS" 
			};
			class Aircraft
			{
				class B_Heli_Light_01_F						{cost = 350;	requirements[]={"H"};	};	// "MH-9 Hummingbird"
				class B_Heli_Transport_01_F					{cost = 800;	requirements[]={"H"};	};	// "UH-80 Ghost Hawk"
				class B_Heli_Transport_03_F					{cost = 1000;	requirements[]={"H"};	};	// "CH-67 Huron"
				class B_Heli_Light_01_dynamicLoadout_F		{cost = 4000;	requirements[]={"H"};	};	// "AH-9 Pawnee"
				class B_UAV_02_dynamicLoadout_F         	{cost = 12000;  requirements[]={"A"};   };  // "Greyhawk"
				class B_Heli_Attack_01_dynamicLoadout_F		{cost = 13000;	requirements[]={"H"};	};	// "AH-99 Blackfoot"
				class B_T_UAV_03_dynamicLoadout_F			{cost = 16000;  requirements[]={"H"};   };  // "Falcon"
				class B_UAV_05_F							{cost = 18000;  requirements[]={"A"};   };  // "Sentinel"
				class B_T_VTOL_01_infantry_F				{cost = 3000;	requirements[]={"A"};	};	// "V-44 X Blackfish(Inf)"
				class B_T_VTOL_01_vehicle_F					{cost = 3000;	requirements[]={"A"};	};	// "V-44 X Blackfish(Vic)"
				class B_T_VTOL_01_armed_F					{cost = 12000;	requirements[]={"A"};	};	// "V-44 X Blackfish (Armed)"
				class B_Plane_CAS_01_dynamicLoadout_F		{cost = 15000;	requirements[]={"A"};	};	// "A-164 Wipeout (CAS)"
				class B_Plane_Fighter_01_F					{cost = 30000;	requirements[]={"A"};	};	// "F/A-181 Black Wasp II"
			};
			class Gear
			{
				class Box_NATO_Ammo_F						{cost = 50;		requirements[]={};	};	// "Basic Ammo [NATO]"
				class Box_NATO_Grenades_F					{cost = 50;		requirements[]={};	};	// "Grenades [NATO]"
				class Box_NATO_Wps_F						{cost = 100;	requirements[]={};	};	// "Basic Weapons [NATO]"
				class Box_NATO_Uniforms_F					{cost = 100;	requirements[]={};	};	// "Uniforms [NATO]"
				class Box_NATO_Equip_F						{cost = 100;	requirements[]={};	};	// "Equipment [NATO]"
				class Box_NATO_AmmoOrd_F					{cost = 300;	requirements[]={};	};	// "Explosives [NATO]"
				class Box_NATO_WpsLaunch_F					{cost = 250;	requirements[]={};	};	// "Launchers [NATO]"
				class Box_NATO_WpsSpecial_F					{cost = 400;	requirements[]={};	};	// "Special Weapons [NATO]"
				class B_supplyCrate_F						{cost = 500;	requirements[]={};	};	// "Supply Box [NATO]"
				class Box_NATO_AmmoVeh_F					{cost = 700;	requirements[]={};	};	// "Vehicle Ammo [NATO]"
				class B_Slingload_01_Ammo_F                 {cost = 2500;   requirements[]={};	};  // "Huron Ammo Container"
				class B_Slingload_01_Repair_F				{cost = 2000;   requirements[]={};	};  // "Huron Repair Container"
				class B_Slingload_01_Fuel_F					{cost = 500;    requirements[]={};	};  // "Huron Fuel Container"
			};
			class Defences
			{
				
				class Land_BagFence_Round_F					{cost = 250;	requirements[]={};	offset[]={0, 2, 0};};	// "Semi Circle Sand bags"  
				class Land_Razorwire_F						{cost = 250;	requirements[]={};	offset[]={0, 5, 0};};	// "Razor Wire Fence"  
				class Land_DragonsTeeth_01_1x1_new_F		{cost = 300;	requirements[]={};	offset[]={0, 2, 0};};	// "Tank barrier"    	  	
				class CamoNet_BLUFOR_big_F					{cost = 250;	requirements[]={};	offset[]={0, 6, 0};};	// "Camouflage Vehicle Cover (Green)"    	
				class Land_IRMaskingCover_01_F				{cost = 500;	requirements[]={};	offset[]={0, 8, 0};};	// "IR Masking Tent (Large)"
				class B_HMG_01_F							{cost = 300;	requirements[]={};	};	// "Mk30 HMG .50"  
				class B_HMG_01_high_F						{cost = 400;	requirements[]={};	};	// "Mk30 HMG .50 (Raised)"  
				class B_GMG_01_F							{cost = 550;	requirements[]={};	};	// "Mk32 GMG 20 mm"  
				class B_GMG_01_high_F						{cost = 650;	requirements[]={};	};	// "Mk32 GMG 20 mm (Raised)"  
				class B_static_AT_F							{cost = 300;	requirements[]={};	};	// "Static Titan Launcher (AT) [NATO]"  
				class B_static_AA_F							{cost = 300;	requirements[]={};	};	// "Static Titan Launcher (AA) [NATO]"  
				class B_Mortar_01_F							{cost = 6500;	requirements[]={};	};	// "Mortar"
				class B_UGV_02_Demining_F					{cost = 100;	requirements[]={};	};	// "UGAS demining"  
				class B_UGV_01_F							{cost = 150;	requirements[]={};	offset[]={0, 3, 0};};	// "UGV Stomper"   
				class B_UGV_01_rcws_F 						{cost = 1000;	requirements[]={};	offset[]={0, 3, 0};};	// "UGAS" 				
				class B_UAV_01_F							{cost = 500;    requirements[]={};	};  // AR-2  
				class B_Radar_System_01_F					{cost = 1000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "AN/MPQ-105 Radar"  
				class B_AAA_System_01_F 					{cost = 5000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Praetorian 1C"  
				class B_SAM_System_01_F						{cost = 15000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Mk49 Spartan"  
				class B_SAM_System_03_F						{cost = 12000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "MIM-145 Defender"  
				class B_SAM_System_02_F						{cost = 20000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Mk21 Centurion"  
				class B_Ship_MRLS_01_F						{cost = 40000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Mk41 VLS"
			};
		};
		class EAST
		{
			class Infantry
			{
				class rhs_msv_emr_rifleman					{cost = 20;		requirements[]={};	};	// "Rifleman"
				class rhs_msv_emr_grenadier					{cost = 25;		requirements[]={};	};	// "Para Trooper"
				class rhs_msv_emr_crew						{cost = 25;		requirements[]={};	};	// "Crewman"
				class rhs_pilot_combat_heli					{cost = 25;		requirements[]={};	};	// "Helicopter Pilot"
				class rhs_msv_emr_medic						{cost = 30;		requirements[]={};	};	// "Combat Life Saver"
				class rhs_msv_emr_grenadier_rpg				{cost = 40;		requirements[]={};	};	// "Grenadier"
				class rhs_msv_emr_arifleman_rpk				{cost = 50;		requirements[]={};	};	// "Autorifleman"
				class rhs_msv_emr_marksman					{cost = 60;		requirements[]={};	};	// "Marksman"
				class rhs_msv_emr_engineer					{cost = 70;		requirements[]={};	};	// "Repair Specialist"
				class rhs_msv_emr_machinegunner				{cost = 80;		requirements[]={};	};	// "Heavy Gunner"
				class rhs_msv_emr_RShG2						{cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class rhs_msv_emr_at						{cost = 150;	requirements[]={};	};	// "Missile Specialist (AT)"
				class rhs_msv_emr_aa						{cost = 200;	requirements[]={};	};	// "Missile Specialist (AA)"
			};
			class Vehicles
			{
				class rhs_uaz_open_MSV_01					{cost = 100;	requirements[]={};	};	// "UAZ-3151 (open)"
				class rhs_tigr_msv							{cost = 300;	requirements[]={};	};	// "GAZ-233011"
				class rhs_tigr_sts_vmf						{cost = 1000;	requirements[]={};	};	// "GAZ-233014"
				class rhs_kamaz5350_msv						{cost = 200;	requirements[]={};	};	// "Kamaz-5350 Transport"
				class rhs_kamaz5350_open_msv				{cost = 200;	requirements[]={};	};	// "Kamaz-5350 (open)"
				class rhs_kamaz5350_ammo_msv				{cost = 500;	requirements[]={};	};	// "Kamaz-5350 Ammo"
				class RHS_Ural_Repair_MSV_01				{cost = 500;	requirements[]={};	};	// "Ural-4320 Repair"
				class RHS_Ural_Fuel_MSV_01					{cost = 500;	requirements[]={};	};	// "Ural-4320 Fuel"
				class RHS_Ural_Zu23_MSV_01            		{cost = 2500;	requirements[]={};	};	// "Ural-4320 Zu23"
				class RHS_BM21_MSV_01						{cost = 8000;	requirements[]={};	};	// "BM-21"
				class rhs_btr60_vmf							{cost = 2000;	requirements[]={};	};	// "BTR-60PB"
				class rhs_btr70_vmf							{cost = 2200;	requirements[]={};	};	// "BTR-70"
				class rhs_btr80_msv							{cost = 2400;	requirements[]={};	};	// "BTR-80"
				class rhs_btr80a_msv						{cost = 2600;	requirements[]={};	};	// "BTR-80A"
				class rhs_bmd1								{cost = 3400;	requirements[]={};	};	// "BMD-1"
				class rhs_bmd1p								{cost = 3600;	requirements[]={};	};	// "BMD-1P"
				class rhs_bmd1pk							{cost = 3000;	requirements[]={};	};	// "BMD-1PK"
				class rhs_bmd1r								{cost = 2000;	requirements[]={};	};	// "BMD-1R"
				class rhs_bmd2								{cost = 4000;	requirements[]={};	};	// "BMD-2"
				class rhs_bmd2m								{cost = 4200;	requirements[]={};	};	// "BMD-2M"
				class rhs_bmd4_vdv							{cost = 4500;	requirements[]={};	};	// "BMD-4"
				class rhs_bmd4m_vdv							{cost = 4500;	requirements[]={};	};	// "BMD-4M"
				class rhs_bmd4ma_vdv						{cost = 4800;	requirements[]={};	};	// "BMD-4M (A)"
				class rhs_bmp1_msv							{cost = 3600;	requirements[]={};	};	// "BMP-1"
				class rhs_bmp1d_msv							{cost = 3800;	requirements[]={};	};	// "BMP-1D"
				class rhs_bmp1k_msv							{cost = 3600;	requirements[]={};	};	// "BMP-1K"
				class rhs_bmp1p_msv							{cost = 3800;	requirements[]={};	};	// "BMP-1P"
				class rhs_bmp2e_msv							{cost = 3800;	requirements[]={};	};	// "BMP-2 (1980)"
				class rhs_bmp2_msv							{cost = 3800;	requirements[]={};	};	// "BMP-2 (1986)"
				class rhs_bmp2d_msv							{cost = 4000;	requirements[]={};	};	// "BMP-2D"
				class rhs_bmp2k_msv							{cost = 3800;	requirements[]={};	};	// "BMP-2K"
				class rhs_bmp3_msv							{cost = 4000;	requirements[]={};	};	// "BMP-3 (early)"
				class rhs_bmp3_late_msv						{cost = 4000;	requirements[]={};	};	// "BMP-3 (late)"
				class rhs_bmp3m_msv							{cost = 4000;	requirements[]={};	};	// "BMP-3 (Vesna-K)"
				class rhs_bmp3mera_msv						{cost = 4100;	requirements[]={};	};	// "BMP-3 (Vesna-K/A)"
				class rhs_brm1k_msv							{cost = 3800;	requirements[]={};	};	// "BRM-1K"
				class rhs_Ob_681_2							{cost = 4000;	requirements[]={};	};	// "Obyekt-681-2"
				class rhs_prp3_msv							{cost = 3000;	requirements[]={};	};	// "PRP-3"
				class rhs_zsu234_aa							{cost = 8000;	requirements[]={};	};	// "ZSU-23-4V"
				class rhs_t72ba_tv							{cost = 9000;	requirements[]={};	};	// "T-72B (1984)"
				class rhs_t72bb_tv							{cost = 9200;	requirements[]={};	};	// "T-72B (1985)"
				class rhs_t72bc_tv							{cost = 9400;	requirements[]={};	};	// "T-72B (1989)"
				class rhs_t72bd_tv							{cost = 9600;	requirements[]={};	};	// "T-72B3 (2012)"
				class rhs_t72be_tv							{cost = 9800;	requirements[]={};	};	// "T-72B3 (2016)"
				class rhs_t80								{cost = 11000;	requirements[]={};	};	// "T-80"
				class rhs_t80a								{cost = 12000;	requirements[]={};	};	// "T-80A"
				class rhs_t80b								{cost = 11000;	requirements[]={};	};	// "T-80B"
				class rhs_t80bv								{cost = 11500;	requirements[]={};	};	// "T-80BV"
				class rhs_t80u								{cost = 12500;	requirements[]={};	};	// "T-80U"
				class rhs_t80u45m							{cost = 13000;	requirements[]={};	};	// "T-80U (45M)"
				class rhs_t80ue1							{cost = 13000;	requirements[]={};	};	// "T-80UE-1"
				class rhs_t80uk								{cost = 13000;	requirements[]={};	};	// "T-80UK"
				class rhs_t80um								{cost = 13000;	requirements[]={};	};	// "T-80UM"
				class rhs_t90_tv							{cost = 14000;	requirements[]={};	};	// "T-90 (1992)"
				class rhs_t90a_tv							{cost = 14500;	requirements[]={};	};	// "T-90A (2006)"
				class rhs_t90am_tv							{cost = 14500;	requirements[]={};	};	// "T-90AM (188AM)"
				class rhs_t90saa_tv							{cost = 14500;	requirements[]={};	};	// "T-90 (2004)"
				class rhs_t90sab_tv							{cost = 15000;	requirements[]={};	};	// "T-90 (2016)"
				class rhs_t90sm_tv							{cost = 15000;	requirements[]={};	};	// "T-90 (188SM)"
				class rhs_sprut_vdv							{cost = 15000;	requirements[]={};	};	// "2S25"
				class rhs_2s1_tv							{cost = 16000;	requirements[]={};	};	// "2S1"
				class rhs_2s3_tv							{cost = 17000;	requirements[]={};	};	// "2S3M1"
				class rhs_9k79								{cost = 20000;	requirements[]={};	};	// "9P129-1M"
				class rhs_t14_tv							{cost = 45000;	requirements[]={};	};	// "T-14"
				class rhs_t15_tv							{cost = 10000;	requirements[]={};	};	// "T-15"
			};
			class Aircraft
			{	  
				class RHS_Mi8T_vvs							{cost = 600;	requirements[]={"H"};	};	// "Mi-8T"
				class RHS_Mi8MT_vvs							{cost = 600;	requirements[]={"H"};	};	// "Mi-8MT"
				class RHS_Mi8AMT_vvs 						{cost = 600;	requirements[]={"H"};	};	// "Mi-8AMT"
				class RHS_Mi8MTV3_vvs						{cost = 6000;	requirements[]={"H"};	};	// "Mi-8MTV-3"
				class RHS_Mi8AMTSh_vvs						{cost = 6500;	requirements[]={"H"};	};	// "Mi-8AMTSh"
				class RHS_Mi24P_vvs							{cost = 7000;	requirements[]={"H"};	};	// "Mi-24P"
				class RHS_Mi24V_vvs							{cost = 7500;	requirements[]={"H"};	};	// "Mi-24V"
				class rhs_mi28n_vvs							{cost = 10000;	requirements[]={"H"};	};	// "Mi-28N"
				class RHS_Ka52_vvsc							{cost = 13000;	requirements[]={"H"};	};	// "Ka-52"
			};
			class Gear
			{
				class rhs_mags_crate						{cost = 50;		requirements[]={};	};	// "Basic Ammo"
				class rhs_weapon_crate						{cost = 100;	requirements[]={};	};	// "Basic Weapons"
				class rhx_gear_crate						{cost = 100;	requirements[]={};	};	// "Equipment"
				class rhs_spec_weapons_crate				{cost = 300;	requirements[]={};	};	// "Explosives"
				class rhs_launcher_crate					{cost = 250;	requirements[]={};	};	// "Launchers"
				class rhs_7ya37_1_single					{cost = 300;	requirements[]={};	};	// "Ak-74"
				class Land_Cargo10_grey_F					{cost = 800;	requirements[]={};	};	// "Vehicle Ammo"
			};
			class Defences
			{
				
				class Land_BagFence_Round_F					{cost = 250;	requirements[]={};	offset[]={0, 2, 0};};	// "Semi Circle Sand bags"  
				class Land_Razorwire_F						{cost = 250;	requirements[]={};	offset[]={0, 5, 0};};	// "Razor Wire Fence"  
				class Land_DragonsTeeth_01_1x1_new_F		{cost = 300;	requirements[]={};	offset[]={0, 2, 0};};	// "Tank barrier"    	 	
				class CamoNet_OPFOR_big_F					{cost = 250;	requirements[]={};	offset[]={0, 6, 0};};	// "Camouflage Vehicle Cover (Hex)"    	
				class Land_IRMaskingCover_01_F				{cost = 500;	requirements[]={};	offset[]={0, 8, 0};};	// "IR Masking Tent (Large)" 
				class RHS_NSV_TriPod_MSV					{cost = 300;	requirements[]={};	offset[]={0, 5.3, 0};};	// "NSV"
				class rhs_KORD_MSV							{cost = 400;	requirements[]={};	offset[]={0, 5.3, 0};};	// "KORD"
				class rhs_KORD_high_MSV						{cost = 400;	requirements[]={};	offset[]={0, 5.3, 0};};	// "KORD (raised)"
				class rhs_Metis_9k115_2_msv					{cost = 500;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Metis-M"
				class rhs_Kornet_9M133_2_msv				{cost = 550;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Kornet-M"   
				class RHS_AGS30_TriPod_MSV					{cost = 550;	requirements[]={};	offset[]={0, 5.3, 0};};	// "AGS-30"  
				class rhs_Igla_AA_pod_msv					{cost = 550;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Igla"  
				class rhs_SPG9M_MSV							{cost = 300;	requirements[]={};	offset[]={0, 5.3, 0};};	// "SPG-9M"
				class rhs_D30_msv							{cost = 6000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "2A18M"
				class RHS_ZU23_MSV							{cost = 1000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "ZU-23-2"
				class rhs_prv13_turret_vpvo					{cost = 1000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "PRV-13"
				class rhs_p37_turret_vpvo					{cost = 1000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "P-37"
				class rhs_2b14_82mm_msv						{cost = 6500;	requirements[]={};	offset[]={0, 5.3, 0};};	// "Mortar"      
				class O_UAV_01_F       						{cost = 500;    requirements[]={};  offset[]={0, 5.3, 0};};  // AR-2
			};
		};
	};
};